name: Multi-Platform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create and display file
        run: |
          echo "This is Ubuntu job" > ubuntu.txt
          cat ubuntu.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: systeminfo
      - name: Create and display file
        run: |
          echo This is Windows job > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create and display file
        run: |
          echo "This is macOS job" > macos.txt
          cat macos.txt

          # workflow trigger test
